serialPort: COM0
renderCapture: true

pokemon:
  lang: en
  notifyShiny: false
  bdsp:
    sendAllEncounters: false
    showBnp: false
    showLastDelay: false
    showLastRunDuration: false
    showMaxDelay: false
